[package]
name = "bitcoin_scripts"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "scripts"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
anyhow = "1.0.90"
bitcoin = { version = "0.32.3", features = ["rand-std"] }
hex = "0.4.3"
