[package]
name = "attestation_server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "att"
path = "src/main.rs"

[dependencies]
schnorr_fun = { version = "0.10", features = ["serde"] }
rand = "0.8.5"
sha2 = "0.10.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
